Bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("account/", include("accounts.urls")),
    path("images/", include("images.urls", namespace="images")),
    path("accounts/", include("allauth.urls")),
    re_path(
        r".*\.js\.map$",
        lambda request: HttpResponse(status=204),
    ),  # Disable sourcemaps
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

action/urls.py
urlpatterns: list = [
    # path("/", .as_view(), name="")
]

images/urls.py
from django.urls import path

from images import views

# Add your code here

app_name = "images"
urlpatterns = [
    path("create/", views.image_create, name="create"),
    path("detail/<int:img_id>/<slug:slug>/", views.image_detail, name="detail"),
    path("like/", views.image_like, name="like"),
    path("", views.image_list, name="list"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  {% load livereload_tags %}

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=0.8" />
    <title>{% block title %}{% endblock title %}</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <script>
      const csrftoken = Cookies.get("csrftoken")
    </script>
    {% block scripts %}
    {% endblock scripts %}
    <script type="text/javascript" src="{% static 'js/darkmode.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'js/close_button.js' %}" defer></script>
  </head>

  <body class="darkmode">
    <div id="header">
      <button id="theme-switch">
        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3"><path d="M480-360q50 0 85-35t35-85q0-50-35-85t-85-35q-50 0-85 35t-35 85q0 50 35 85t85 35Zm0 80q-83 0-141.5-58.5T280-480q0-83 58.5-141.5T480-680q83 0 141.5 58.5T680-480q0 83-58.5 141.5T480-280ZM200-440H40v-80h160v80Zm720 0H760v-80h160v80ZM440-760v-160h80v160h-80Zm0 720v-160h80v160h-80ZM256-650l-101-97 57-59 96 100-52 56Zm492 496-97-101 53-55 101 97-57 59Zm-98-550 97-101 59 57-100 96-56-52ZM154-212l101-97 55 53-97 101-59-57Zm326-268Z"/></svg>
        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e3e3e3"><path d="M480-120q-150 0-255-105T120-480q0-150 105-255t255-105q14 0 27.5 1t26.5 3q-41 29-65.5 75.5T444-660q0 90 63 153t153 63q55 0 101-24.5t75-65.5q2 13 3 26.5t1 27.5q0 150-105 255T480-120Zm0-80q88 0 158-48.5T740-375q-20 5-40 8t-40 3q-123 0-209.5-86.5T364-660q0-20 3-40t8-40q-78 32-126.5 102T200-480q0 116 82 198t198 82Zm-10-270Z"/></svg>
      </button>
      <a href="{% url 'dashboard' %}"><span class="logo">Bookmarks</span></a>
      {% if request.user.is_authenticated %}
      <ul class="menu">
        <li {% if section == "dashboard" %} class="selected" {% endif %}><a href="{% url 'dashboard' %}">Dashboard</a></li>
        <li {% if section == "images" %} class="selected" {% endif %}><a href="{% url 'images:list' %}">Images</a></li>
        <li {% if section == "people" %} class="selected" {% endif %}><a href="{% url 'user_list' %}">People</a></li>
      </ul>
      {% endif %}
      <span class="user">
        {% if request.user.is_authenticated %}
          <form action="{% url 'logout' %}" method="post">{% csrf_token %}
            Hello {{request.user.first_name|default:request.user.username}}&nbsp;
            <button type="submit">Logout</button>
          </form>
        {% else %}
          <a href="{% url 'login' %}">Log-in</a>
        {% endif %}
      </span>
    </div>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li class="{{message.tags}}">
            {{message|safe}}
            <a href="#" class="close">x</a>
          </li>
        {% endfor %}
      </ul>
    {% endif %}
    <div id="content">{% block content %}{% endblock content %}</div>
  </body>

</html>