Bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("account/", include("accounts.urls")),
    path("images/", include("images.urls", namespace="images")),
    path("accounts/", include("allauth.urls")),
    re_path(
        r".*\.js\.map$",
        lambda request: HttpResponse(status=204),
    ),  # Disable sourcemaps
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

action/urls.py
urlpatterns: list = [
    # path("/", .as_view(), name="")
]

images/urls.py
from django.urls import path

from images import views

# Add your code here

app_name = "images"
urlpatterns = [
    path("create/", views.image_create, name="create"),
    path("detail/<int:img_id>/<slug:slug>/", views.image_detail, name="detail"),
    path("like/", views.image_like, name="like"),
    path("", views.image_list, name="list"),
]

images/models.py
from cloudinary.models import CloudinaryField
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.


class Image(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="images_created",
        on_delete=models.CASCADE,
    )
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="images_liked",
        blank=True,
    )
    title = models.CharField(max_length=200, default="")
    slug = models.SlugField(max_length=200, blank=True, auto_created=True)
    url = models.URLField(max_length=2000, blank=True)
    image = CloudinaryField(
        "image",
        blank=True,
        folder="Social_Website/media/images/",
        default="https://res.cloudinary.com/dd1qoripz/image/upload/v1745813449/No_Image_Available_wvog0c.jpg",
        transformation={
            "width": 300,
            "height": 300,
            "crop": "fill",
            "quality": "auto",
            "fetch_format": "auto",
        },
    )
    description = models.TextField(blank=True)
    created_at = models.DateField(auto_now_add=True)
    total_likes = models.PositiveIntegerField(default=0)
    total_views = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            models.Index(fields=["created_at"]),
            models.Index(fields=["-total_likes"]),
        ]
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs) -> None:  # noqa: ANN002, ANN003
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        return reverse(
            "images:detail",
            args=[self.pk, self.slug],
        )

images/forms.py
import cloudinary
import cloudinary.uploader
from django import forms
from django.utils.text import slugify

from images.models import Image

MAX_TITLE_LENGTH = 50


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["title", "url", "description"]
        widgets = {
            "url": forms.HiddenInput,
        }

    def clean_url(self) -> str:
        url = self.cleaned_data["url"]
        valid_extensions = ["jpg", "jpeg", "png"]
        extension = url.rsplit(".", 1)[1].lower()
        if extension not in valid_extensions:
            error_message = "The given URL does not match valid image extensions."
            raise forms.ValidationError(error_message)
        return url

    def save(self, commit: bool = True) -> Image:
        image: Image = super().save(commit=False)
        image_url = self.cleaned_data["url"]
        image_title = (
            self.cleaned_data["title"]
            if len(self.cleaned_data["title"]) < MAX_TITLE_LENGTH
            else self.cleaned_data["title"][:MAX_TITLE_LENGTH] + "..."
        )
        image_description = self.cleaned_data["description"]
        name = slugify(image.title)
        # extension = image_url.rsplit(".", 1)[1].lower()
        # image_name = f"{name}.{extension}"
        upload_result = cloudinary.uploader.upload(
            image_url,
            folder="Social_Website/media/images/",
        )
        image.title = image_title
        image.slug = name
        image.description = image_description
        image.image = upload_result["secure_url"]

        if commit:
            image.save()
        return image

images/views.py
from __future__ import annotations

from typing import TYPE_CHECKING

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, Paginator
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponsePermanentRedirect,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, redirect, render

from accounts.views import cast
from action.models import Action
from images.forms import ImageCreateForm
from images.models import Image

if TYPE_CHECKING:
    from common.stubs import ExtendedImage, ExtendedUser


@login_required
def image_create(
    request: HttpRequest,
) -> HttpResponseRedirect | HttpResponsePermanentRedirect | HttpResponse:
    user = User.objects.get(pk=request.user.pk)

    if request.method == "POST":
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            Action.create_action(user, "Bookmarked image", new_image)
            messages.success(request, "Image added successfully")
            return redirect(new_image.get_absolute_url())
        messages.error(request, "The formulary wasn't valid, please submit valid data")
    else:
        form = ImageCreateForm(data=request.GET)

    return render(
        request,
        "images/create.html",
        {
            "section": "images",
            "form": form,
        },
    )


def image_detail(request: HttpRequest, img_id: int, slug: str) -> HttpResponse:
    image = get_object_or_404(Image, pk=img_id, slug=slug)
    viewed_images = request.session.get("viewed_images", [])

    if image.pk not in viewed_images:
        image.total_views += 1
        image.save()
        viewed_images.append(image.pk)
        request.session["viewed_images"] = viewed_images

    return render(
        request,
        "images/detail.html",
        {
            "section": "images",
            "image": image,
            "total_views": image.total_views,
        },
    )


@login_required
def image_like(request: HttpRequest) -> JsonResponse:
    image_id = request.POST.get("id")
    action = request.POST.get("action")
    user: ExtendedUser = cast("ExtendedUser", User.objects.get(pk=request.user.pk))

    if not image_id or not action:
        return JsonResponse({
            "status": "error",
            "details": "Image ID and Action required",
        })

    try:
        image: ExtendedImage = cast("ExtendedImage", Image.objects.get(id=image_id))
        if action == "like":
            image.users_like.add(user)
            Action.create_action(user, "Like", image)
        else:
            image.users_like.remove(user)
            Action.create_action(user, "Dislike", image)
        users_like = [
            {
                "first_name": user.first_name,
                "profile_photo": (
                    user.profile.photo.url if user.profile.photo else None
                ),
                "profile_url": user.get_absolute_url(),
            }
            for user in image.users_like.select_related("profile").all()
        ]
        return JsonResponse({"status": "ok", "users_like": users_like})
    except Image.DoesNotExist:
        return JsonResponse({"status": "error", "details": "Image doesn't exist"})


@login_required
def image_list(request: HttpRequest) -> HttpResponse:
    images = Image.objects.all()
    paginator = Paginator(images, 3)
    page = request.GET.get("page")
    images_only = request.GET.get("images_only")
    try:
        images = paginator.page(page or 1)
    except EmptyPage:
        if images_only:
            return HttpResponse("")
        images = paginator.page(paginator.num_pages)
    if images_only:
        return render(
            request,
            "images/list_images.html",
            {"section": "images", "images": images},
        )
    return render(
        request,
        "images/list.html",
        {"section": "images", "images": images},
    )

templates/images/create.html
{% extends 'base.html' %}

{% block title %} Bookmark an image {% endblock title%}

{% block content %}
  <h1>Bookmark an image</h1>
  <img src="{{request.GET.url}}" alt="" class="image-preview">
  <form action="" method="post"> {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Bookmark it!">
  </form>
{% endblock content %}

templates/images/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ image.title }}
{% endblock %}

{% block scripts %}
  <script type="module" src="{% static 'js/anchorAction.js' %}" defer></script>
  <script type="module" src="{% static 'js/image_like.js' %}" defer></script>
{% endblock %}

{% block content %}
  <h1>{{ image.title }}</h1>
  <a href="{{ image.image.url }}"><img src="{{ image.image.url }}" alt="" class="image-detail" /></a>
  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count"><span class="total">{{ total_likes }} like{{ total_likes|pluralize }}</span></span>
        <span class="count">{{ total_views }} view{{ total_views|pluralize }}</span>
        <a href="{% url 'images:like' %}" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}dis{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Dislike
          {% endif %}
        </a>
      </div>
      <p class="image-detail">{{ image.description }}</p>
    </div>
    <div class="image-likes" id="image-likes">
      <p class="image-detail">Users Like:</p>
      {% for user in image.users_like.all %}
        <div>
          {% if user.profile.photo %}
            <a href="{{ user.get_absolute_url }}"><img src="{{ user.profile.photo.url }}" alt="" /></a>
          {% endif %}
          <p>
            <a href="{{ user.get_absolute_url }}">{{ user.first_name }}</a>
          </p>
        </div>
      {% empty %}
        <div>
          <p>Nobody likes this image yet</p>
        </div>
      {% endfor %}
    </div>
  {% endwith %}
{% endblock %}

templates/images/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Images bookmarked
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="{% static 'js/paginator.js' %}" defer></script>
{% endblock %}

{% block content %}
  <h1>Images bookmarked</h1>
  <div id="image-list">
    {% include 'images/list_images.html' %}
  </div>
{% endblock %}

templates/images/list_images.html
{% if images %}
  {% for image in images %}
    <div class="image">
      <a href="{{ image.get_absolute_url }}">
        <a class="image-detail-photo" href="{{ image.get_absolute_url }}"><img src="{{ image.image.url }}" alt="" /></a>
      </a>
      <div class="info">
        <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
      </div>
    </div>
  {% endfor %}
{% else %}
  <p class="image-detail">No images uploaded yet.</p>
{% endif %}